## Chicago Housing Prices Dataset

What is the price of 1342 N Leavitt Street? It's located in Wicker Park, a single-family home with two baths. The home is a 10-minute drive from the loop at 3.96 miles to Lake Michigan. The local crime index is 3.76 and the local school index is 16.7. The house is 116 years old. The lot size is 3,049 sqft and the house size is 3,154 sqft.


In [29]:
import pandas as pd
from sklearn import cross_validation
# import K-Nearest-Neighbor classifier
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.filterwarnings('ignore')

# show plots inline
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (7, 3)
plt.rcParams['font.size'] = 12
from matplotlib.colors import ListedColormap
cmap_bold = ListedColormap(['#FF0000', '#00FF00', '#0000FF'])

In [54]:
house = pd.read_csv('hw2-chicago.csv')
print('Dimensions of the data:', house.shape)

('Dimensions of the data:', (219, 12))


In [55]:
house.head()

Address Neighborhood          HouseType   Price  \
0   2111 W Division St #5, Chicago IL  Wicker Park              Condo  390000   
1     1520 W Walton St #2, Chicago IL  Wicker Park              Condo  320500   
2        2047 W Thomas St, Chicago IL  Wicker Park  Multi-Family Home  620000   
3  1735 N Paulina St #314, Chicago IL  Wicker Park              Condo  318000   
4        1634 W Beach Ave, Chicago IL  Wicker Park  Multi-Family Home  477000   

   Bath  CrimeIndex  MinutesToLoop  MilesToLake  Age  LotSizeSqft  \
0   NaN        2.59              9         3.91    0            0   
1   NaN        4.10              7         3.02    0            0   
2   4.0        2.09              9         3.84   94         3049   
3   NaN        2.40              9         2.90    0            0   
4   2.0        4.63              9         2.96   31         2614   

   HouseSizeSqft  SchoolIndex  
0              0         36.2  
1              0         91.7  
2           3492         36.2  
3              0         50.0  
4           1840         78.9

In [56]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 12 columns):
Address          219 non-null object
Neighborhood     219 non-null object
HouseType        216 non-null object
Price            219 non-null int64
Bath             70 non-null float64
CrimeIndex       219 non-null float64
MinutesToLoop    219 non-null int64
MilesToLake      219 non-null float64
Age              219 non-null int64
LotSizeSqft      219 non-null int64
HouseSizeSqft    219 non-null int64
SchoolIndex      219 non-null float64
dtypes: float64(4), int64(5), object(3)
memory usage: 20.6+ KB


In [57]:
house['Leavitt'] = ""

In [58]:
house['Leavitt'] [house['Address'].str.contains("Leavitt")] = 1
house.head()

Address Neighborhood          HouseType   Price  \
0   2111 W Division St #5, Chicago IL  Wicker Park              Condo  390000   
1     1520 W Walton St #2, Chicago IL  Wicker Park              Condo  320500   
2        2047 W Thomas St, Chicago IL  Wicker Park  Multi-Family Home  620000   
3  1735 N Paulina St #314, Chicago IL  Wicker Park              Condo  318000   
4        1634 W Beach Ave, Chicago IL  Wicker Park  Multi-Family Home  477000   

   Bath  CrimeIndex  MinutesToLoop  MilesToLake  Age  LotSizeSqft  \
0   NaN        2.59              9         3.91    0            0   
1   NaN        4.10              7         3.02    0            0   
2   4.0        2.09              9         3.84   94         3049   
3   NaN        2.40              9         2.90    0            0   
4   2.0        4.63              9         2.96   31         2614   

   HouseSizeSqft  SchoolIndex Leavitt  
0              0         36.2          
1              0         91.7          
2           3492         36.2          
3              0         50.0          
4           1840         78.9

In [63]:
house2 = house[house['Leavitt'] == 1]
print(house2.shape)
house2.head()

(5, 13)


Address Neighborhood           HouseType  \
53       1507 N Leavitt St, Chicago IL  Wicker Park  Single-Family Home   
68    1431 N Leavitt St #1, Chicago IL  Wicker Park               Condo   
104  1056 N Leavitt St #2F, Chicago IL  Wicker Park               Condo   
117   1427 N Leavitt St #2, Chicago IL  Wicker Park               Condo   
200      1338 N Leavitt St, Chicago IL  Wicker Park  Single-Family Home   

      Price  Bath  CrimeIndex  MinutesToLoop  MilesToLake  Age  LotSizeSqft  \
53   245000   1.0        3.51             10         3.86  121         3485   
68   300000   NaN        4.26             11         3.90    0            0   
104  303000   NaN        2.46             10         4.12    0            0   
117  320000   NaN        4.26             11         3.90    0            0   
200  322000   1.0        3.76             10         3.97  126         3049   

     HouseSizeSqft  SchoolIndex Leavitt  
53             861         93.9       1  
68               0         16.7       1  
104              0         36.2       1  
117              0         16.7       1  
200           1260         16.7       1

In [67]:
house2 = house2.fillna(0)

In [68]:
house2['HouseType'].unique()

array(['Single-Family Home', 'Condo'], dtype=object)

In [70]:
house2['HouseType_num'] = house2['HouseType'].map({'Single-Family Home':1, 'Condo':2})
del house2['HouseType']
del house2['Neighborhood']
del house2['Address']

In [85]:
y = house2['Price'].values
X = house2.drop('Price', axis=1).values
knn = KNeighborsClassifier(n_neighbors =5)
knn.fit(X,y)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [86]:
house2.columns

Index([u'Price', u'Bath', u'CrimeIndex', u'MinutesToLoop', u'MilesToLake',
       u'Age', u'LotSizeSqft', u'HouseSizeSqft', u'SchoolIndex', u'Leavitt',
       u'HouseType_num'],
      dtype='object')

### Use the description provided, do the prediction

What is the price of 1342 N Leavitt Street? It's located in Wicker Park, a single-family home with two baths. The home is a 10-minute drive from the loop at 3.96 miles to Lake Michigan. The local crime index is 3.76 and the local school index is 16.7. The house is 116 years old. The lot size is 3,049 sqft and the house size is 3,154 sqft.

In [87]:
X_new = (2, 3.76, 10, 3.96, 116,3049, 3154, 16.7, 1, 1)
new_prediction = knn.predict(X_new)
print("Prediction: {}".format(new_prediction))

Prediction: [245000]
